with PU_DO_TABLE AS
(SELECT 
FT.PICKUP_DATE_SK,
FT.PICKUP_TIME_SK,
FT.DROPOFF_DATE_SK,
DD.DATE_VALUE,
DD.YEAR || '-' ||DD.MONTH_OF_YEAR AS YEAR_MONTH,
FT.DROPOFF_TIME_SK,
FT.PASSENGER_COUNT,
FT.DURATION_SECONDS,
FT.TRIP_DISTANCE,
FT.TRIP_DISTANCE_MT,
FT.PULOCATIONID,
DZ1.BOROUGH_NAME AS PU_BOROUGH,
DZ1.SERVICE_ZONE_NAME AS PU_SERVICE_ZONE,
DZ1.ZONE_NAME AS PU_ZONE_NAME,
FT.DOLOCATIONID,
DZ2.BOROUGH_NAME AS DO_BOROUGH,
DZ2.SERVICE_ZONE_NAME AS DO_SERVICE_ZONE,
DZ2.ZONE_NAME AS DO_ZONE_NAME,
FT.PAYMENT_TYPE_ID,
FT.FARE_AMOUNT,
FT.EXTRA,
FT.MTA_TAX,
FT.TIP_AMOUNT,
FT.TOLLS_AMOUNT,
FT.IMPROVEMENT_SURCHARGE,
FT.TOTAL_AMOUNT,
FT.CONGESTION_SURCHARGE
FROM NYC_YELLOW.TRIPS_GOLD.FACT_TRIP FT
LEFT JOIN NYC_YELLOW.TRIPS_GOLD.DIM_ZONE DZ1 ON (FT.PULOCATIONID = DZ1.LOCATIONID)
LEFT JOIN NYC_YELLOW.TRIPS_GOLD.DIM_ZONE DZ2 ON (FT.DOLOCATIONID = DZ2.LOCATIONID)
LEFT JOIN NYC_YELLOW.TRIPS_GOLD.DIM_DATE DD  ON (FT.DROPOFF_DATE_SK = DD.DATE_SK)
)
,
agg_pu_do_table AS(
SELECT
YEAR_MONTH,
PULOCATIONID || '-' || DOLOCATIONID AS FROM_TO_LOC,
PU_BOROUGH,
PU_SERVICE_ZONE,
PU_ZONE_NAME,
DO_BOROUGH,
DO_SERVICE_ZONE,
DO_ZONE_NAME,
RANK() OVER (PARTITION BY YEAR_MONTH ORDER BY COUNT(*) DESC) AS COUNT_RANK,
COUNT(*) AS TRIP_COUNT,
SUM(TOTAL_AMOUNT) AS TOTAL_AMOUNT,
SUM(FARE_AMOUNT) AS FARE_AMOUNT
FROM PU_DO_TABLE
GROUP BY
YEAR_MONTH,
PULOCATIONID || '-' || DOLOCATIONID,
PU_BOROUGH,
PU_SERVICE_ZONE,
PU_ZONE_NAME,
DO_BOROUGH,
DO_SERVICE_ZONE,
DO_ZONE_NAME)


SELECT 
FR.YEAR_MONTH,
FR.COUNT_RANK,
FR.FROM_TO_LOC,
FR.PU_BOROUGH || '-' || FR.PU_ZONE_NAME AS PU_BOR_ZONE,
FR.DO_BOROUGH || '-' || FR.DO_ZONE_NAME AS DO_BOR_ZONE,
FR.TRIP_COUNT
FROM AGG_PU_DO_TABLE FR
WHERE
FR.COUNT_RANK <= 10
AND YEAR_MONTH NOT IN ('2024-12','2025-3')
ORDER BY FR.YEAR_MONTH, FR.COUNT_RANK