/*
TRIPS_SILVER TABLES CREATION
*/

/*
TRIPS_CLEANED
This table is used to store the cleaned trip data.
It is created from the TRIPS_RAW table and contains only the necessary fields for analysis.
*/


CREATE or replace TABLE NYC_YELLOW.TRIPS_SILVER.TRIP_CLEANED (
	VENDORID NUMBER(38,0),
	PICKUP_DATETIME TIMESTAMP_NTZ(6),
	DROPOFF_DATETIME TIMESTAMP_NTZ(6),
	PASSENGER_COUNT NUMBER(38,0),
	TRIP_DISTANCE FLOAT,
    TRIP_DISTANCE_MT FLOAT,
    TRIP_DISTANCE_KM FLOAT,
	RATECODEID NUMBER(38,0),
	STORE_AND_FWD_FLAG VARCHAR(10),
	PULOCATIONID NUMBER(38,0),
	DOLOCATIONID NUMBER(38,0),
	PAYMENT_TYPE NUMBER(38,0),
	FARE_AMOUNT FLOAT,
	EXTRA FLOAT,
	MTA_TAX FLOAT,
	TIP_AMOUNT FLOAT,
	TOLLS_AMOUNT FLOAT,
	IMPROVEMENT_SURCHARGE FLOAT,
	TOTAL_AMOUNT FLOAT,
	CONGESTION_SURCHARGE FLOAT,
	AIRPORT_FEE FLOAT,
	CBD_CONGESTION_FEE FLOAT
);


INSERT INTO NYC_YELLOW.TRIPS_SILVER.TRIP_CLEANED
(VENDORID, PICKUP_DATETIME, DROPOFF_DATETIME, PASSENGER_COUNT, TRIP_DISTANCE, TRIP_DISTANCE_MT,
 TRIP_DISTANCE_KM, RATECODEID, STORE_AND_FWD_FLAG, PULOCATIONID, DOLOCATIONID, PAYMENT_TYPE,
 FARE_AMOUNT, EXTRA, MTA_TAX, TIP_AMOUNT, TOLLS_AMOUNT, IMPROVEMENT_SURCHARGE, TOTAL_AMOUNT,
 CONGESTION_SURCHARGE, AIRPORT_FEE, CBD_CONGESTION_FEE)


WITH trip_cleaned as (
select 
tr.vendorid,
TO_TIMESTAMP_NTZ (tpep_pickup_datetime / 1000000) AS pickup_datetime,
TO_TIMESTAMP_NTZ (tpep_dropoff_datetime / 1000000) AS dropoff_datetime,
tr.passenger_count,
tr.trip_distance,
tr.trip_distance*1609.34 as TRIP_DISTANCE_MT,
tr.trip_distance*1.60934 as TRIP_DISTANCE_KM,
tr.ratecodeid,
tr.store_and_fwd_flag,
tr.pulocationid,
tr.dolocationid,
tr.payment_type,
tr.fare_amount,
tr.extra,
tr.mta_tax,
tr.tip_amount,
tr.tolls_amount,
tr.improvement_surcharge,
tr.total_amount,
tr.congestion_surcharge,
tr.airport_fee,
tr.cbd_congestion_fee
from NYC_YELLOW.TRIPS_BRONZE.YELLOW_TRIPDATA as tr
where
IFNULL(tr.fare_amount,0) > 0
)

select 
VENDORID,
PICKUP_DATETIME,
DROPOFF_DATETIME,
PASSENGER_COUNT,
TRIP_DISTANCE,
TRIP_DISTANCE_MT,
TRIP_DISTANCE_KM,
RATECODEID,
STORE_AND_FWD_FLAG,
PULOCATIONID,
DOLOCATIONID,
PAYMENT_TYPE,
FARE_AMOUNT,
EXTRA,
MTA_TAX,
TIP_AMOUNT,
TOLLS_AMOUNT,
IMPROVEMENT_SURCHARGE,
TOTAL_AMOUNT,
CONGESTION_SURCHARGE,
AIRPORT_FEE,
CBD_CONGESTION_FEE 
from trip_cleaned;