/*
TRIPS_SILVER TABLES CREATION
*/

/*
TRIPS_CLEANED
This table is used to store the cleaned trip data.
It is created from the TRIPS_RAW table and contains only the necessary fields for analysis.
*/


CREATE TABLE IF NOT EXISTS TRIPS_CLEANED (
 	VENDORID NUMBER(38,0),
	PICKUP_DATETIME DATETIME,
	DROPOFF_DATETIME DATETIME,
	PASSENGER_COUNT NUMBER(38,0),
	TRIP_DISTANCE FLOAT,
	RATECODEID NUMBER(38,0),
	STORE_AND_FWD_FLAG VARCHAR(),
	PULOCATIONID NUMBER(38,0),
	DOLOCATIONID NUMBER(38,0),
	PAYMENT_TYPE NUMBER(38,0),
	FARE_AMOUNT FLOAT,
	EXTRA FLOAT,
	MTA_TAX FLOAT,
	TIP_AMOUNT FLOAT,
	TOLLS_AMOUNT FLOAT,
	IMPROVEMENT_SURCHARGE FLOAT,
	TOTAL_AMOUNT FLOAT,
	CONGESTION_SURCHARGE FLOAT,
	AIRPORT_FEE FLOAT,
	CBD_CONGESTION_FEE FLOAT
)  